### ISSUE TITLE
Can't seem to add api routes

### ISSUE THREAD

**Issue by michaelryancaputo** [RickWong/react-isomorphic-starterkit#10]
Can't seem to add custom api routes in the src/server.js file. Every request seems to be intercepted by the React Router at this level.

**Comment by RickWong** [comment]
A very valid question, thanks. On which line are you now defining your new API route? You should put it _above_ the static folder "catch all" route. Another adjustment that would help is to detect API routes in `onPreResponse` and `reply.continue()` instead of firing up React Router.

**Comment by michaelryancaputo** [comment]
Got it, ok, i was able to get it running by putting my route above the catch all, and using a /api/{params} slug. I didn't think of trying to intercept with "onPreResponse".

You might want to add in some documentation for others who are tying to do a similar thing.

Thanks for the quick reply, great generator, i've already passed it along to some friends.

**Comment by guido4000** [comment]
> You should put it above the static folder "catch all" route.

One question: why is the sample route for the github request below the catch all route instead of above?
