### ISSUE TITLE
.babelrc and postLoaders?

### ISSUE THREAD

**Issue by amcsi** [RickWong/react-isomorphic-starterkit#101]
I have two questions:
1. How come you aren't configuring babel with a .babelrc, and instead using postLoaders?
2. Why are you using postLoaders instead of regular loaders for babel?

**Comment by RickWong** [comment]
1. I find .babelrc an unnecessary extra file. I like the Babel configuration within the Webpack configuration, together.
2. Because it's easier to replace postLoaders in the `-watch.js` files.

**Comment by amcsi** [comment]
Thanks!
