### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by ironweber** [RickWong/react-isomorphic-starterkit#103]
Great stuff you are doing here!

I was wondering if you have attempted or figured out how to do inline images with either url-loader or the file-loader isomorphicly ...

```
var imagePath = require('./images/image.jpg');
```

and in Reacts render method ... 

```
render() {
  ...
    <img src={imagePath} />
  ...
}
```

I run my css through the NormalModuleReplacementPlugin and node-noop but can't do that with images because server side the `imagePath` variable will be an object that gets converted to a string e.g. `[object Object]`

```
new webpack.NormalModuleReplacementPlugin(/\.(css|scss)$/, 'node-noop')
```

I end up getting two of the same image when the same component runs through my server (express with react-router) and client webpack configs. It saves to `./dist/assets` and to `./dist/server output paths. I have tried to just get it to save to the assets folder but to no avail.

Would be nice to see how people are managing inline images in components server side ...

**Comment by RickWong** [comment]
No I haven't explored this yet. Do you think it's better or more convenient than just serving the files from `/static`?

**Comment by chrisblossom** [comment]
@ironweber post any updates you may have found.

Building the backend with webpack should be able to replace the need for https://github.com/halt-hammerzeit/webpack-isomorphic-tools

**Comment by RickWong** [comment]
@ironweber I've updated the starterkit to include `file-loader` and rewrote the favicon parts to import the `ico` file as URL string to use on server and client.
