### ISSUE TITLE
On client side, render() only run after all Transmit fragments completed?

### ISSUE THREAD

**Issue by ngduc** [RickWong/react-isomorphic-starterkit#110]
Hi,
After server rendering & user navigates (client routes) & comes back to Main,
render() only run after all Transmit fragments completed?

If I have some slow fragments, there will be a delay (flickering) before user can see the component. Is there a way to make it render() first, then once all the fragments completed, it can refresh the view with data (like 2-way binding)? Thanks.

**Comment by RickWong** [comment]
You can use deferred fragments, simply by returning a Promise-function in the fragment that can be fetched later. If you're using ES6 that means just wrapping the fragment with `() => { ... }`

**Comment by ngduc** [comment]
Thank you Rick!
I managed to make this work. Now, data is fetched normally both on server & client with no flickering issue. (async)
Do you think this approach work?

```
const _fetchInitialData = (id) => {
  return githubApi.read(['posts', id], {}).then(json => json).catch(error => { throw error; });
};

class Home extends React.Component {
  state = { data: {}, commentBoxData: {} };

  componentWillMount () {     // after routing back to this component, manually fetch data:
    if (__CLIENT__ && !this.props.data) {
      _fetchInitialData(1).then((res) => this.setState({ data: res }));
    } else {
      this.setState(this.props);
    }
  }
  render() {
    return (<div>
            <div>Post 1 - Title: "{this.state.data.title}"</div>
        </div>);
  }
}
export default Transmit.createContainer(Home, {
  initialVariables: {},
  fragments: {
    data: () => ( __CLIENT__ ? Promise.resolve() : _fetchInitialData(1))
  }
});
```

**Comment by RickWong** [comment]
Yeah @ngduc this should work great.

Only the `.then(json => json)` part is redundant as it does nothing. Also it's perhaps best not to do something like `setState(this.props)` because the component should either manage state (as a container) accept props and render (as a component).
