### ISSUE TITLE
Code only renders on server.

### ISSUE THREAD

**Issue by nuclearspike** [RickWong/react-isomorphic-starterkit#122]
This line in server.js is wrong:

const webserver = **PRODUCTION** ? "" : `//${this.hostname}:8080`;

8080 is the webpack dev server port being used, the const 'webserver' is used in the template code to tell the browser where to pull client.js, and it's not on 8080. So, when you run the code, it does the server-side render, but can't do client-side because that code is never downloaded, it gets a 404.

**Comment by kulikalov** [comment]
Take a look at client.js, line 6

**Comment by nuclearspike** [comment]
`import routesContainer from "containers/routes";`?

I am not sure how this relates.
