### ISSUE TITLE
Timed out waiting for dist/*.js after 30 seconds

### ISSUE THREAD

**Issue by chuntley** [RickWong/react-isomorphic-starterkit#126]
On OSX, after running `npm run watch` I periodically get the error:

`Timed out waiting for dist/*.js after 30 seconds`
`npm run watch-server-start exited with code null`
`Sending SIGTERM to other processes..`

The server never starts because of this, so I end up having to rerun the watch command. If I run watch, then change a couple of files, sometimes it will catch the change and run the server. Any ideas on what could be causing this?

**Comment by neilkyoung** [comment]
Every now and again I get issues when running `npm run watch`. To resolve this I normally just remove all the hot update files (*.js, *.map & *.json) in that directory and it resolves the issues.

**Comment by johneisenheim** [comment]
Hi there!
I experienced the same problem! In my case, I solved increasing the just-wait time in package.json. 

`"watch-server-start": "node node_modules/just-wait -t 50000 --pattern \"dist/*.js\" && npm run start"`.
