### ISSUE TITLE
 Error: Cannot find module "babel-runtime/helpers"

### ISSUE THREAD

**Issue by kutzi** [RickWong/react-isomorphic-starterkit#16]
Tried the newest version and I'm now getting
 Error: Cannot find module "babel-runtime/helpers"

when running npm run watch

**Comment by RickWong** [comment]
Did you install the new dependencies? If that doesn't help then the easiest fix is probably to delete the `node_modules` directory and run `npm install` again.

**Comment by kutzi** [comment]
I've created a clean new Docker container, so everything specified should be installed

**Comment by RickWong** [comment]
Just did a test by running this:

```
git clone https://github.com/RickWong/react-isomorphic-starterkit.git
cd react-isomorphic-starterkit
npm install -g supervisor webpack webpack-dev-server concurrently
npm install
npm run watch     # yes, one command for server and client development!
```

In my `/tmp` and it worked like a charm. :/

**Comment by kutzi** [comment]
Ok, thanks for checking.
I'll try it again later -  am currently working on something different.
I thought there might be something obvious missing.

**Comment by RickWong** [comment]
Ok, hope it works!
