### ISSUE TITLE
npm 2.x should mean we don't need the -g installs anymore

### ISSUE THREAD

**Issue by Pomax** [RickWong/react-isomorphic-starterkit#17]
The `npm install -g supervisor webpack webpack-dev-server concurrently` install command should, with node 12 and npm 2.5+, now simply be a matter of having those four dependencies marked as dependencies, with `npm install` making those commands available when run from the project's directory. Additionally, github does [release](http://git-scm.com/book/en/v2/Git-Basics-Tagging) tags, so you don't need to clone a repo just to use it when it's a standalone project like this one. It simply makes a .zip/tar file available for people to grab without even needing git. Superhandy.

**Comment by RickWong** [comment]
Thanks Mike!
