### ISSUE TITLE
(React Router) pushState doesn't seem to work 

### ISSUE THREAD

**Issue by MickCoelho** [RickWong/react-isomorphic-starterkit#18]
When updating the route to something like that: 

```
<Route path="/" handler={Main} >
        <Route name="page1" handler={Page1}/>
        <Route name="page2" handler={Page2}/>
</Route>
```

The ReactRouter doesn't seem to take advantages of pushState and rewrite the full html page (reloads all the scripts attached to it).

**Comment by RickWong** [comment]
How do you render the links? Can you show me that code?

**Comment by MickCoelho** [comment]
Ok, that's actually fine.
Was using the links the wrong way, my bad!

**Comment by RickWong** [comment]
Okay cool, thanks for reporting back.
