### ISSUE TITLE
(io.js) npm install failed on iojs

### ISSUE THREAD

**Issue by asendia** [RickWong/react-isomorphic-starterkit#19]
Hi there,

I couldn't get it installed in iojs 1.6.2 but it run flawlessly in node 0.12.1
Does it have something to do with v8?

../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
  void SetResourceConstraints(Isolate\* isolate, ResourceConstraints\* constraints) {
       ^
make: **\* [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/home/myhome/react-isomorphic-starterkit/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/myhome/iojs-v1.6.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Linux 3.16.0-33-generic
gyp ERR! command "/home/myhome/iojs-v1.6.2-linux-x64/bin/iojs" "/home/myhome/iojs-v1.6.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/myhome/react-isomorphic-starterkit/node_modules/fibers
gyp ERR! node -v v1.6.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
Build failed

**Comment by RickWong** [comment]
Thanks for reporting this. I think this node-fibers issue is related: https://github.com/laverdet/node-fibers/issues/203

For now I suggest only using the starterkit with node. I'm also researching the Relay-approach for fetching data with higher-order components: https://github.com/RickWong/react-transmit It's a cleaner solution so the starterkit wouldn't need the `react-async` and `fibers` dependencies anymore.

**Comment by RickWong** [comment]
OK, `react-async` and its `fibers` dependency are gone. The starterkit now uses React Transmit for data fetching and isomorphism.

I've tested io.js support again. It worked like a charm.
