### ISSUE TITLE
Use Flux

### ISSUE THREAD

**Issue by doodledood** [RickWong/react-isomorphic-starterkit#21]
It would be nice if the starter kit made use of Facebook's Flux or some Flux library like Reflux.

**Comment by RickWong** [comment]
Please see this issue https://github.com/RickWong/react-isomorphic-starterkit/issues/4

There's still not a winner in the Flux libraries space. Even Reflux that I quite like too, is still figuring out how to do isomorphic support. https://github.com/spoike/refluxjs/issues/144

**Comment by doodledood** [comment]
I see.
Have you considered using one of the following implementations? 
- http://fluxible.io/
- https://goatslacker.github.io/alt/

Both seem interesting and support isomorphic apps out of the box.

**Comment by RickWong** [comment]
Yeah I'll take a better look at those.

There's also:
- https://github.com/BinaryMuse/fluxxor
- https://github.com/acdlite/flummox
- https://github.com/malte-wessel/minimal-flux

**Comment by iam4x** [comment]
I went for Alt with Iso for isormorphic flux, here's my boilerplate: https://github.com/iam4x/isomorphic-flux-boilerplate

**Comment by RickWong** [comment]
I'm still not convinced that the starterkit must include a Flux implementation. All the Flux libraries are simply an `npm install ...` away, so everyone can just use what they're comfortable with. 

Right now the starterkit has a polyfill for the Fetch API, and React Transmit for isomorphic data fetching. As soon as Facebook releases [Relay](https://www.npmjs.com/package/react-relay) I will consider moving to Relay + GraphQL.
