### ISSUE TITLE
What is the recommended way of routing to a React component that isn't wrapped by Transmit?

### ISSUE THREAD

**Issue by Azaeres** [RickWong/react-isomorphic-starterkit#22]
For example, in `views/Main.js`, taking the Transmit code out and replacing the Transmit container export with `export default Main;` causes the server to fail to reply, which might be related to how the server currently expects to use Transmit.

One thing I did try (with `react-transmit` v2.5.0) was replacing the Transmit container export with `export default Transmit.createContainer(Main);`, basically a container with no queries, but even that continued to hang until I took the conditional out of https://github.com/RickWong/react-transmit/blob/b96b4abab914ebe84e44f53d00234ac656914d5c/src/lib/createContainer.js#L75.  However, this doesn't seem like the ideal way of going about things since in this case I'm wrapping the React component with a Transmit container that I'm not using.

What do you recommend?

**Comment by RickWong** [comment]
Sounds like a bug in Transmit's `renderToString()` implementation. Will fix it asap.

**Comment by RickWong** [comment]
Ryan, I just released `react-transmit@2.5.3`. Unfortunately it doesn't directly solve your problem. You still have to either A. wrap `Main` with `Transmit.createContainer(Main)` or B. use `React.render()` in `server.js` instead, if there isn't a single Transmit container in your whole component tree.

**Comment by Azaeres** [comment]
Thanks for the quick reply, Rick.  Works for me. :+1:
