### ISSUE TITLE
Can't access webpack-dev-server :8080 from Vagrant

### ISSUE THREAD

**Issue by joeframbach** [RickWong/react-isomorphic-starterkit#27]
Steps:
1. `vagrant init "ubuntu/trusty64"`.
2. Modify Vagrantfile to add port 8000 and 8080 to be accessible by host.
3. `vagrant up`
4. `vagrant ssh`
5. git clone github...react-isomorphic-starterkit, cd, npm install -g, npm install
6. Instead of `npm run watch`, which will fail because there is no browser/VT available, run:
   -  `npm run watch-client` # in one tab
   -  `npm run start` # in another tab

Result: http://localhost:8000/ looks great and shows the static result correctly, but throws a **404** on http://localhost:8080/dist/client.js

Problem: `http://localhost:8080/dist/client.js` can't be found by the host. If I instead run `python -m SimpleHTTPServer 8080` or `http-server -p8080`, then `http://localhost:8080/dist/client.js` is found. It just looks like `webpack-dev-server` isn't listening to requests from the host?

**Comment by joeframbach** [comment]
Solved!

I added `host: "0.0.0.0"` to the `config.devServer` config in `webpack.client-watch.js`.

**Comment by Jakobud** [comment]
I have the same issue. I've never heard of `webpack.client-watch.js`. What is that? I am new to Webpack and I've only been using `webpack.config.js` so far...

**Comment by brainthinks** [comment]
@Jakobud - when you run webpack from the terminal, you can specify a file that isn't named `webpack.config.js` - [webpack CLI docs](http://webpack.github.io/docs/cli.html#configuration-file-config-example-config-js).

**Comment by ZhangHanDong** [comment]
it does work:

'''
webpack-dev-server --host 0.0.0.0
'''

**Comment by ZhangHanDong** [comment]
it does work:

'''
webpack-dev-server --host 0.0.0.0
'''
