### ISSUE TITLE
ES6 modules!

### ISSUE THREAD

**Issue by madlotus** [RickWong/react-isomorphic-starterkit#3]
The goal for ECMAScript 6 modules was to create a format that both users of CommonJS and of AMD are happy with:

Similar to CommonJS, they have a compact syntax, a preference for single exports and support for cyclic dependencies.
Similar to AMD, they have direct support for asynchronous loading and configurable module loading.
Being built into the language allows ES6 modules to go beyond CommonJS and AMD (details are explained later):

Their syntax is even more compact than CommonJS’s.
Their structure can be statically analyzed (for static checking, optimization, etc.).
Their support for cyclic dependencies is better than CommonJS’s.
The ES6 module standard has two parts:

Declarative syntax (for importing and exporting)
Programmatic loader API: to configure how modules are loaded and to conditionally load modules

so, is it possible to use ES6 modules with this starter kit? it will be awesome, thanks man.

**Comment by RickWong** [comment]
You mean `import Something from "something";` ? I have plans to use that syntax in the future, when Babel.js supports importing it like `Something` is an const/immutable symbol. 

Right now `const Something = require("something");` is the user-friendlier syntax.

**Comment by RickWong** [comment]
Relates to https://github.com/babel/babel/issues/954

**Comment by madlotus** [comment]
great @RickWong 

keep it up! :+1:
