### ISSUE TITLE
Im having issues , in windows 

### ISSUE THREAD

**Issue by doronaviguy** [RickWong/react-isomorphic-starterkit#34]
Is there windows support, or it just me ?

**Comment by doronaviguy** [comment]
**OS: WINDOWS 64Bit | node -v v0.10.38**
I can run the project only after changing this steps:
- RUN  set NODE_PATH=./src 
- Change path in all the require declarations 
  in views/Routes => import Main from ""views/Main" to "./Main";
  in client.js => import routes from "views/Routes" to "./views/Routes";
  in server.js => import routes from "views/Routes" to "./views/Routes";

i understand it somtehing has to do with NODE_PATH.
After these steps all works fine .

**Comment by RickWong** [comment]
Windows support is a bit lacking, I confess, because I don't know the shell environment that well. Also see https://github.com/RickWong/react-isomorphic-starterkit/issues/1
