### ISSUE TITLE
(Webpack) Replace piping with Webpack HMR

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-isomorphic-starterkit#38]
Discussion started here: https://github.com/RickWong/react-isomorphic-starterkit/issues/36#issuecomment-103816919 with @ericfong

The idea is to bring back `webpack.server.js` (watch & production builds) and use Webpack's Hot Module Reload mechanism for watching changes on the server-side. If it's faster then it will be a more consistent and widely supported replacement for piping.

**Comment by ericfong** [comment]
+1

**Comment by RickWong** [comment]
Tiny update at https://github.com/RickWong/react-isomorphic-starterkit/issues/41#issuecomment-107740396

**Comment by mozmorris** [comment]
:+1: 

@RickWong, what was the reason for moving away from `webpack.server.js` in the first place?

**Comment by monte-hayward** [comment]
+1

**Comment by Download** [comment]
What are your ideas on this?
As I understand it, Webpack HMR works by running a small script in the browser that receives updates from Webpack and applies them.

My research so far suggests we would need `webpack-dev-middleware` along with `webpack-hot-middleware`. At least it seems that [gaeron](https://github.com/gaearon) is heading in that path.

Closest I've come to seeing a working setup for this is this project: [glenjamin/ultimate-hot-reloading-example](https://github.com/glenjamin/ultimate-hot-reloading-example). In his [server.js](https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L42), he does this:

``` js
// Do "hot-reloading" of express stuff on the server
// Throw away cached modules and re-require next time
// Ensure there's no important state in there!
var watcher = chokidar.watch('./server');
watcher.on('ready', function() {
  watcher.on('all', function() {
    console.log("Clearing /server/ module cache from server");
    Object.keys(require.cache).forEach(function(id) {
      if (/\/server\//.test(id)) delete require.cache[id];
    });
  });
});
```

I am not that into all this stuff, but from what I can gather from this snippet, it seems he is wiping the `require.cache`, meaning the code will be reloaded when it's next `require`d.

In my normal coding style that would be never, but I think this explains why in the snippet just above he is doing the `require` call inside `app.use`:

``` js
// Anything else gets passed to the client app's server rendering
app.get('*', function(req, res, next) {
  require('./client/server-render')(req.path, function(err, page) {
    if (err) return next(err);
    res.send(page);
  });
});
```

This seems to work quitte nicely. I do see two problems:
1. This approach is quite blunt. It would probably perform a lot better if he could somehow only blow out the cache for those modules that have actually changed.
2. He is requiring `babel-register` at the top of the file, which hooks babel into the require mechanism... This is great for being able to use es6/7 features in Node, but it also means that on every reload, all these modules are transpiled all over again... Which sounds expensive, especially considering that Webpack is already doing exactly the same for the client bundle. 

If only we somehow could use the same code that webpack emits on the Node JS side as well that would be fantastic. But I have no idea whether that is possible and/or if someone is working on it.

Any ideas?

**Comment by Download** [comment]
Relevant info:
- [webpack/docs - hot module replacement with webpack](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack)
- [webpack/docs - How to HMR on server side? #45](https://github.com/webpack/docs/issues/45)
- [jiyinyiyong/webpack-backend-HMR-demo](https://github.com/jiyinyiyong/webpack-backend-HMR-demo)
- [Backend Apps with Webpack (Part I)
  March 16, 2015](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)
- [Backend Apps with Webpack: Driving with Gulp (Part II)](http://jlongster.com/Backend-Apps-with-Webpack--Part-II)
- [Live Editing JavaScript with Webpack (Part III)](http://jlongster.com/Backend-Apps-with-Webpack--Part-III)

**Comment by RickWong** [comment]
I've been studying this one by @jlongster: https://github.com/jlongster/backend-with-webpack Though it does not support every type of exported module, because it uses monkey-hot-loader that only updates the changed file. I believe in one of the above articles it says that full webpack HMR bubbling changes up the require-chain is also possible, but I haven't seen that in the wild.

We actually do need Babel's require-hook if we want to support css-modules and other non-JS imports.

So Webpack HMR is optional (as proven by @glenjamin's example) but I do think their HMR API is more battle-tested than a DIY one. And Babel is mandatory.

I'm having a hard time trying to find time to experiment with these set-ups. Would love to get help on this! Anything is appreciated.

**Comment by Download** [comment]
Lol I was just reading his three 'Backend Apps with Webpack' articles. Great stuff, but indeed not very battle tested.

As for babel's require hook, I still don't see why you would need it. If you indeed use Webpack to bundle up the backend just like you do the frontend you would be able to get CSS modules support from there right?

Really, the guys from webpack, react-hot-loader and express/koa should join forces to tackle this issue once and for all.... A guy can dream can't he?  :)

**Comment by RickWong** [comment]
It took a while but the server-side now uses Webpack too. That means many webpack loaders should work on the server as well including `url-loader` and `css-loader`. (Piping is also gone, the server gets instant code updates from Webpack HMR!)

So please try release ^5.0.0.

**Comment by Download** [comment]
Cool! I just got server-side Webpack working yesterday as well, but will def. check this out. Thank you!

**Comment by chemoish** [comment]
@RickWong What are your thoughts on https://github.com/webpack/docs/issues/45#issuecomment-149793458?

> You can't use existing HMR loaders like react-hot-loader or style-loader because they make no sense in a server environment. Just add manuall replacement code at the correct location (i. e. accept request handler like in the example)

Is it too much overhead to just include `react-transform-hmr` and be done with it?

**Comment by RickWong** [comment]
You don't need React HMR because Webpack HMR is enough for the server. The reason React HMR exists is because on the client, you want to keep the rendered components' states (this.state and this.props), but update their logic (render). That's what React HMR does. On the server each http request is preferably stateless. Webpack HMR replaces the components entirely without keeping state, and that's just fine!

For style, I have tried to use style-loader but it stupidly attempts to put <link ...> in a DOM. But there's no DOM on the server. It should rather give us a string "<link ...>" that we can serve out ourselves. I may fork style-loader myself to do this.
