### ISSUE TITLE
Add Redux?

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-isomorphic-starterkit#45]
I've been following the [Redux](https://github.com/gaearon/redux) project a bit, and it seems that [people really like it](https://github.com/acdlite/flummox/blob/master/README.md) as well.

Might be smart to hold this off until their API stabilizes some more.

**Comment by RickWong** [comment]
Never mind. Let the user decide what to use.

**Comment by luandro** [comment]
I really like this starterkit for it's simplicity, but adding a flux implementation (I've tried [Alt](https://github.com/goatslacker/alt) and [Redux](https://github.com/gaearon/redux)) to the isomorphic mix has resulted only in frustration for me. Could someone shed some light on how this should be accomplished?
