### ISSUE TITLE
(Transmit) How do populate transmit differently for client and server.

### ISSUE THREAD

**Issue by jorgelo** [RickWong/react-isomorphic-starterkit#48]
First off, this is amazing. I've been playing with it and I've run into a problem that I cannot find the solution for. Let's say I want to load data via an AJAX call on the client, but on the server I want to hit the database. How would I take different actions? Now, if I check for the _CLIENT / _SERVER globals, that works, but when webpacked all the server code gets shipped to the user.

Is there a way to control this?

Here is a very basis example of what I'd like to do.

```
class Person extends React.Component {
    render () {
        return (
            <div>{this.props.person.name}</div>
        );
    }
}

export default Transmit.createContainer(Person, {
    queries: {
        person (queryParams) {
          //If server, load from the database
          //If client, load from ajax call
        }
    }
});
```

**Comment by kevzettler** [comment]
This is handled in the defualt example:

https://github.com/RickWong/react-isomorphic-starterkit/blob/master/src/views/Main.js#L147-L184

you can use `__CLIENT__` and `__SERVER__` in your `person` function to act accordingly. 

The example calls the github api directly in a `__SERVER__` context and uses a proxy in `__CLIENT__` context

according to this comment
https://github.com/RickWong/react-isomorphic-starterkit/blob/master/src/views/Main.js#L14-L17
The build is supposed to strip out `__SERVER__` blocks from the client build

If you can confirm thats not happening that sounds like a huge bug

**Comment by RickWong** [comment]
@jorgelo Does the above answer your question? Use `if (__SERVER__ / __CLIENT__)` blocks to adapt to the running environment.
