### ISSUE TITLE
(Transmit) React router not passing QueryParams to Transmit?

### ISSUE THREAD

**Issue by kevzettler** [RickWong/react-isomorphic-starterkit#49]
I hope Im overlooking something simple I feel like this should be straight forward. I have some react router routes

```
import React from "react";
import {Route, DefaultRoute} from "react-router";
import Main from "views/Main";
import Connect from "views/Connect";

export default (
  <Route path="/">
    <DefaultRoute handler={Main} />
    <Route path="/connect/:id" handler={Connect}/>
  </Route>
);
```

I then have `Connect` handler

```
import React from "react";
import Transmit from "react-transmit";
import { Navbar,Button } from "react-bootstrap";
import Promise from "bluebird";

const request = require('superagent-promise')(require('superagent'), Promise);

class Connect extends React.Component {

  render (){
    return (
      <div>
        <Navbar></Navbar>
          <form>
            <input type="text" />
          </form>
      </div>
    )
  }

}

export default Transmit.createContainer(Connect, {
  queries: {
      test (queryParams){
        console.log("wtf queryParams*****", queryParams, this);
      }
  }
});
```

`queryParams` is always empty in the `test` function. I was hoping to pull `:id` from the react router route to pass in to one of the Transmit queries

**Comment by kevzettler** [comment]
@RickWong any thoughts or guidance on this?

Seems similar to https://github.com/RickWong/react-transmit/issues/10

Which dosen't look like it was properly resolved

**Comment by RickWong** [comment]
Hi @kevzettler I would recommend writing a new `ConnectHandler` component that handles the route, captures the id, then renders `<Connect queryParams={{id}} />`. It functions as a bridge between React Router and the Transmit component. 

Although it's one more component to write, it does separate routing from the Connect component. Doing it like this, enables you to re-use the Connect component somewhere else with another id.

**Comment by aksrikanth** [comment]
Hi @RickWong 

Sorry to bring up this old, bug but your workaround doesn't seem to work for me. Am I doing something wrong here:

**Comment by aksrikanth** [comment]
Hi @RickWong,

Maybe I'm missing something, but your workaround doesn't seem to work for me. Here is what I did

```
// Routes
<Route name="user" path="/user/:userId" handler={IdProxy} />

// in IdProxy
render() {
  return <User userId={this.props.params.userId} />
}

// in User (ES6 syntax)
class User extends React.Component {
  render() {
    const user = this.props.user;
    console.log('p: ', this.props);
    return <div/>;
  }
}

export default Transmit.createContainer(User, {
  queries: {
    user(queryParams) {
      console.log('qp: ', queryParams);
      return new Promise((resolve, reject) => {
        resolve(1);
      });
    }
  }
});
```

This still ends up with the props containing the userId but the queryParams being blank. If I need to load a user in the queries, I cannot without the userId.

**Comment by RickWong** [comment]
You should render the User like this: `<User queryParams={{userId: this.props.params.userId}} />`. See this DOCS section [HOC PropTypes](https://github.com/RickWong/react-transmit/blob/master/DOCS.md#api-transmitcontainer-higher-order-component).

**Comment by aksrikanth** [comment]
Thanks for clarifying :)
