### ISSUE TITLE
Fatal error on load

### ISSUE THREAD

**Issue by mcrider** [RickWong/react-isomorphic-starterkit#5]
I'm not able to get this to start up.  After loading the entry point, I get this error in the log:

```
WARNING in ./~/hapi/~/vision/lib/manager.js
Critical dependencies:
251:33-46 the request of a dependency is an expression
 @ ./~/hapi/~/vision/lib/manager.js 251:33-46
```

I've run npm update reinstalled the app, but no dice.

**Comment by RickWong** [comment]
I get that too. Haven't invested in fixing it. It's a webpack warning that shouldn't be fatal. Do you see anything on http://localhost:8000/ ?

**Comment by mcrider** [comment]
No, that page can't be reached.  The webpack dev server runs on 8080, though it looks like its missing some pieces (haven't run webpack before so not sure what it should look like).

![screen shot 2015-03-05 at 10 04 31 am](https://cloud.githubusercontent.com/assets/130554/6507309/261cc264-c31f-11e4-814f-f2c12326c044.png)

**Comment by RickWong** [comment]
The screenshot of :8080 looks correct. But what's logged into `./tmp/server.log` and `./tmp/supervisor.log` Pretty sure there's a different error somewhere in the logs.

**Comment by mcrider** [comment]
Ah, there we go -- apparently I didn't have supervisor installed globally.  Installed and all is well now.  Thanks for your help!
