### ISSUE TITLE
Authentication / Session management with isomorfism

### ISSUE THREAD

**Issue by kalken** [RickWong/react-isomorphic-starterkit#51]
Hello!

Has anybody done authentication with this? I was hoping to use hapi-auth-cookie and maybe hapi-bell for user logins, but its not really clear how to handle cookies with serverside rendering and client side rendering. Any pointers to how to do it would be appreciated. 
/K

**Comment by kalken** [comment]
On second note i think that this would be a great addon to the starterkit demopage. To be able to see how authentication and server rendering should fit together with react-transmit. (e.g) i can not think of an application with this kind of setup that does not require login/session management at some point.

**Comment by antilect** [comment]
+1. A working authentication and authorization example would make this starterkit look really attractive.

**Comment by aksrikanth** [comment]
+1. I was trying to figure out how authentication would work isomorphically.

**Comment by guido4000** [comment]
+1

**Comment by tylermadison** [comment]
In server.js you can check for cookies in the 'onPreResponse' by using the `request.state` e.g. `request.state.someCookie` and `reply.redirect()` accordingly...http://hapijs.com/tutorials/cookies

**Comment by Dindaleon** [comment]
What about using one of these: https://github.com/nelsonic/learn-hapi#authentication

**Comment by priyankpat** [comment]
What if we were to use JSON Web Tokens for Authentication? The Server can decode and verify the token: https://jwt.io/

**Comment by Dindaleon** [comment]
@kalken @antilect you can check my repo for the implementation, I am using JWT, hapi-auth-cookie, and redis to store user data. Please let me know what you think.

https://github.com/Dindaleon/hapi-react-starter-kit
