### ISSUE TITLE
(Transmit) Using RoutHandler...

### ISSUE THREAD

**Issue by tylermadison** [RickWong/react-isomorphic-starterkit#54]
How does this work with RouteHandler? I am running into issues where the DefaultRoute is a Transmit.Container and contains the `<RouteHandler />` component. When  a route changes with a `<Link />` the page goes blank and replaces the inside of the `<Router>` tag with an `<undefinedContainer>` tag

**Comment by tylermadison** [comment]
Thought it was an issue with not including `<RouteHandler />` in nested routes, but still having the same issue, although when refreshing the page on a given nested route components render as expected...

**Comment by tylermadison** [comment]
@RickWong Still not working. Can someone link me to a fork that shows how to set this up correctly? The problem is the starter kit only has the `<DefaultRoute handler={Main}/>` set, and I don't see the usage of any ``<RouteHandler />`'s

Thanks!

**Comment by tylermadison** [comment]
Related to #56

**Comment by RickWong** [comment]
Support for React Router 1.0.0 deprecates this issue.
