### ISSUE TITLE
(Transmit/Routing) this.props.setQueryParams must be called in componentWillMount or routing does not work properly...

### ISSUE THREAD

**Issue by tylermadison** [RickWong/react-isomorphic-starterkit#56]
In Main.js `componentWillMount()` method in the `if(__CLIENT__) { }` block if you take out the additional call to `this.props.setQueryParams({...etc})` routes do not behave properly.

**Comment by RickWong** [comment]
I can't reproduce this issue in the latest release. There have been some changes under the hood. Reopen if this is still an issue.

**Comment by tmadison-gpsw** [comment]
This is still an issue in the latest version. If you have a nested route and navigate to it via a `<Link />` it re-renders both components. If you call `this.props.transmit.forceFetch({})` in `componentWillMount` in the `Main` component,  the routes work as expected and do not cause the re-render.

In Routes.js

``` javascript
export default (
  <Router>
    <Route path="/" component={Main}>
      <Route path=":id" component={Detail} />
    </Route>
  </Router>
);
```
