### ISSUE TITLE
Will this be updated to use Relay proper?

### ISSUE THREAD

**Issue by kevzettler** [RickWong/react-isomorphic-starterkit#59]
Any plans?

**Comment by RickWong** [comment]
I'm still going through the freshly released Relay docs. As I go through it more and more, I'll try to make the decision. For now it seems that Relay brings in a lot of new concepts that the community hasn't heard of yet. For example Relay Routes, fragments, and the general dependency on GraphQL and the availability of a GraphQL server. And there's also the question how isomorphic/universal Relay works...

Please share your opinions here.

**Comment by kevzettler** [comment]
@RickWong I agree. I feel theres a lot of value to your `react-transmit` library. Value in that it is Promise based and utilizes the HOC pattern. I don't think GraphQL will become widely adopted anytime soon and looks like Relay has a hard dependency on it for now.

**Comment by RickWong** [comment]
Actually spoke to Relay devs on reactiflux#relay and the conclusion seems to be there's no "done" hook comparable to Transmit's `onQuery` that receives the resolved data, allowing another `React.renderToString` call once more _with_ the resolved data. Basically that means Relay will only render loading spinners on the server for now. 

Correct me if I'm wrong. I've looked at Relay's `onReadyStateChange` but that doesn't seem to be sufficient for server rendering.

**Comment by apazzolini** [comment]
Likely dependent on https://github.com/facebook/relay/issues/136. 

Additionally, the overview of Relay's `preload` mode described [in this comment](https://github.com/facebook/relay/issues/36#issuecomment-130402024) is especially interesting and could likely be applied to `react-transmit`.

**Comment by RickWong** [comment]
`preload mode` sounds great for mostly client-side apps. I'm a bit sceptical though for server-side. The true worth of a universal/isomorphic app is that first output is complete.

I'll definitely look into it for Transmit. Thanks.
