### ISSUE TITLE
hapi view engine suggestion?

### ISSUE THREAD

**Issue by paOol** [RickWong/react-isomorphic-starterkit#63]
Has there been any consideration in using Hapi React Views (https://github.com/jedireza/hapi-react-views) as the hapi view engine to render .jsx?

Or would that interfere with React Router? 

I think this line 
`Transmit.renderToString(Handler).`
would no longer be necessary with hapi-react-views?

**Comment by RickWong** [comment]
Thanks for the suggestion! I don't want to make the starterkit very Hapi-specific, so this won't fit.

Of course if people want to use hapi-react-views, they can add it themselves.
