### ISSUE TITLE
Help needed with nested routes

### ISSUE THREAD

**Issue by edimoldovan** [RickWong/react-isomorphic-starterkit#64]
Hi,

So I tried out this starter kit, which I like a lot as it gives me a really nice, small toolkit for trying out isomorphic apps.

However, I ran into an issue. Tried adding nested routes, like this

``` html
<Route path="/">
    <DefaultRoute name="home" handler={Main}/>
    <Route name=“list" path=“list" handler={List}>
        <Route name=“list-detail" path=“detail" handler={ListDetail}>
    <Route/>
</Route>
```

Then added a the route handler into the markup of the List component. Everything is fine, except for one thing: If I reload the page on a route different then `/`, the navigation doesn’t work anymore, nothing is rendered when I click any on the links.

This is how the links look like:

``` html
<Link to="home">Home</Link>
<Link to=“list”>List</Link>
<Link to=“list-detail”>Detail</Link>
```

Does anyone have a nested routing example for this setup? I am not getting any error, so I am a bit confused on what could be wrong.

Thanks,
Eduárd

**Comment by tylermadison** [comment]
@edimoldovan Can you share your repo? I was having similar issues and I think I figured it out.

**Comment by edimoldovan** [comment]
@tylermadison I don’t have a repo right now. Let me put one together today and get back to you on that.
Thanks a lot!

**Comment by edimoldovan** [comment]
@tylermadison I put the repo together here: https://github.com/edimoldovan/isomorphic

**Comment by tylermadison** [comment]
@edimoldovan @RickWong Looks like in each of the parent routes you must call `this.props.setQueryParams({});` in the `componentWillMount` method when running on the `__CLIENT__` whether or not you need additional data fetching. Try this and let me know if that works, I believe it's related to #56

``` javascript
  componentWillMount () {
    if (__SERVER__) {

      /**
       * This is only run on the server, and will be removed from the client build.
       */
      console.log("Hello server");
    }

    if (__CLIENT__) {
      this.props.setQueryParams({});

      /**
       * This is only run on the client.
       */
      console.log("Hello client");

    }
  }
```

**Comment by edimoldovan** [comment]
You were right, that fixed it. Thanks a lot!

**Comment by tylermadison** [comment]
@edimoldovan Great, also if you don't need the parent route to be a Transmit container i.e. 

``` javascript
export default Component;
```

vs.

``` javascript
export default Transmit.createContainer(Component, ...etc);
```

You don't have to call `this.props.setQueryParams` in `componentWillMount`

**Comment by edimoldovan** [comment]
Yes, I probably don’t but I have look into that when I go on building the app.
