### ISSUE TITLE
window.__reactTransmitPacket === undefined

### ISSUE THREAD

**Issue by tylermadison** [RickWong/react-isomorphic-starterkit#65]
On server side render the `window.__reactTransmitPacket` on the client is undefined...any ideas on how to access that data via the client? I have confirmed valid JSON etc.

**Comment by RickWong** [comment]
https://github.com/RickWong/react-transmit/blob/61dd806bad83a6840e78115903fc88f035a9a0b9/src/lib/render.js#L16

After `Transmit.render()` the packet is deleted. View the page's source to see if the packet was served to the client on-load.

**Comment by tylermadison** [comment]
Awesome thanks @RickWong , I realized that you can get to that data via `this.props.media` in `componentWillMount` which is the whole point doh!
