### ISSUE TITLE
Is it a bug or a feature? Using regular components alongside with Transmitter containers makes app not respond on server load.

### ISSUE THREAD

**Issue by Webkadabra** [RickWong/react-isomorphic-starterkit#66]
For example, I've added just one page to react-isomorphic-starterkit, Like so:

`RegularPage.js`:

```
class RegPage extends React.Component {
    /**
     * Runs on server and client.
     */
    render () {
        return (
            <div namespace="RegPage">
                <h1>
                    REGULAR PAGE
                </h1>
            </div>
        );
    }
}
export default RegPage;
```

Then, added it to `routes`:

```
export default (
    <Route path="/">
        <DefaultRoute handler={Main} />
        <Route name="RegularPage" path="RegularPage" handler={RegularPage} />
    </Route>
);
```

Noiw, if I start a server and go to `http://localhost:8000/RegularPage` - I just get infinite page loading. Issue goes away if I wrap "RegularPAge" in transmit wrapper (without queries even, just a wrapper). I'm fairly new to node, advice is appreciated!

**Comment by RickWong** [comment]
How do you render the root component?

**Comment by Webkadabra** [comment]
Everything else is clean checkout of react-isomorphic-starterkit, nothing changed.

**Comment by Webkadabra** [comment]
Also, if you add <Link> from {Main} component to this "RegularPage", open up http://localhost:8000 and then follow a link to "RegularPage", then "regularPage" will get rendered (but refreshing page at http://localhost:8000/ReglarPage still produces infinite loading and no results)

**Comment by tylermadison** [comment]
@Webkadabra It seems to me that any top level route handler must be a Transmit Container even if it has no queries associated with it: `export default Transmit.createContainer(RegularPage)`

**Comment by RickWong** [comment]
@tylermadison is right. In `server.js` you can see that `Transmit.renderToString` is used. Therefore the root React component must be a Transmit container.
