### ISSUE TITLE
(React Transform) suggestion: update react router / webpack dev server

### ISSUE THREAD

**Issue by paOol** [RickWong/react-isomorphic-starterkit#68]
React Router is on v1 rc now and React transform (https://github.com/gaearon/react-transform-boilerplate) is basically a better HMR tool.

I think these would make good additions to this starterkit.

**Comment by RickWong** [comment]
Thanks. I've actually already got React 0.14-rc1 and React Router 1.0.0 working locally. Will release it this week. Then I'll definitely look at React Transform.

**Comment by RickWong** [comment]
Related to #38.

**Comment by tylermadison** [comment]
This would be awesome. :+1:

**Comment by Dindaleon** [comment]
I already got this one (with react transform) working just now. There is only a tiny issue that I havent been able to solve. When manually refreshing the browser, I get the following Warning:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server: 
```

The version on the server wont update.

**EDIT:** Fixed. I will soon post it.

**Comment by ericjuta** [comment]
Any updates? @Dindaleon

**Comment by Dindaleon** [comment]
@rej156 here you go https://github.com/Dindaleon/hapi-react-starter-kit

**Comment by RickWong** [comment]
We are now using React Router v1 and React Transform HMRE.

**Comment by tizmagik** [comment]
@Dindaleon I'm having a similar issue on another app I'm working on. Were you able to pin-point exactly what needed to change to get the server to update (and avoid that reuse markup warning?)

**Comment by Dindaleon** [comment]
@tizmagik react transform and hot reloading on client are working ok on my current setup. However, I am having some difficulties with Webpack and hot reloading on server. Changes are seen on the client but if I refresh the page, the server was not updated eventhough webpack rebundled the modified modules. Thus giving an error about reuse markup until I manually reload webpack's server. So, I am still working on it.

I see that Rick managed to get it working by going back to `webpack-dev-server` I tried it but it gives me an error when rendering the page.

```
Uncaught TypeError: Cannot read property 'replace' of null
```

I get that error on Rick's kit as well when running `npm run watch`

Look at this ticket: https://github.com/RickWong/react-isomorphic-starterkit/issues/90

**Comment by tizmagik** [comment]
@Dindaleon I actually have the same issue. Client hot loading working fine, but the server doesn't seem to update (which produces the React server side markup is different warning). I thought it was just because I didn't configure the hot-reloading on the server correctly, but it's unclear what's going on.

I _think_ that error you mentioned happens when you've basically enabled hot reloading twice (e.g. once in webpack config or via using `webpack-dev-server` and then once from the CLI, `--hot` for example).

Anyway, I'm working on this same issue as well, please ping me if you make any progress. I'll do likewise. Do you have a project up somewhere so I can poke around?

**Comment by Dindaleon** [comment]
@tizmagik sure, I will let you know if I find a solution.

This is my current project https://github.com/Dindaleon/hapi-react-starter-kit

It began as a starter kit but it is evolving into something bigger. If you want to contribute please do so.
