### ISSUE TITLE
(Node 0.10) Unable to run after initial installation steps

### ISSUE THREAD

**Issue by bdefore** [RickWong/react-isomorphic-starterkit#7]
I get the following output from the final step of npm run watch: https://gist.github.com/bdefore/9d1570ed9c2345f201ca

It opens the browser to localhost:8000 but nothing comes up

**Comment by RickWong** [comment]
Might be that the browser opened before the node server started listening for connections. Have you tried refreshing  after a few seconds?

**Comment by bdefore** [comment]
Sorry for the delay in responding. Refreshing minutes later didn't make a difference. I wasn't ever able to get the server to startup.

**Comment by bdefore** [comment]
Ah ha. Runs fine on 0.12. I was running 0.10.

**Comment by RickWong** [comment]
Thanks for reporting this. :+1:
