### ISSUE TITLE
Navigation?

### ISSUE THREAD

**Issue by myndzi** [RickWong/react-isomorphic-starterkit#72]
This looks like a really neat project, I'm giving it a spin. It'll take a little while to understand a number of the pieces, but one thing right off the bat that is really unclear is the entry point for rendering with regards to navigation.

How should I be handling components that are static across the breadth of the site? Do I just re-include them in every page that is a route target? That seems a little bit inconvenient.

**Comment by tylermadison** [comment]
I was thinking the same thing I cannot get a working example of nested routing, what route definition pattern is this using now? https://github.com/RickWong/react-isomorphic-starterkit/blob/master/src/views/routes.js#L7

**Comment by RickWong** [comment]
React Router 1.0 supports pure JS object definitions as routes. Though most of the examples still use the `<Router>...</Router>` JSX notation. I'll see what I can do.

**Comment by RickWong** [comment]
@myndzi You probably want nested routes.

https://github.com/rackt/react-router/blob/9ab07526f40cbdf07b0d2c63a585c9dd29e96978/examples/shared-root/app.js#L72-L82

The parent route would then simply render its static parts and then its routed children.

https://github.com/rackt/react-router/blob/9ab07526f40cbdf07b0d2c63a585c9dd29e96978/examples/shared-root/app.js#L19

**Comment by tylermadison** [comment]
:+1:
