### ISSUE TITLE
No clean URLs in 3.0.1

### ISSUE THREAD

**Issue by guido4000** [RickWong/react-isomorphic-starterkit#74]
When starting the boilerplate on localhost the URL gets rewritten with a hash a unique param (e.g. http://localhost:8000/#/?_k=6pzz4k). How can this be disabled?

**Comment by RickWong** [comment]
The fix for these weird URLs is pending in PR https://github.com/RickWong/react-isomorphic-starterkit/pull/71 

I'll try to merge it today.

**Comment by guido4000** [comment]
Perfect. Fixed.
