### ISSUE TITLE
Fails for all browsers that don't natively support Promises. 

### ISSUE THREAD

**Issue by Jimtattersall** [RickWong/react-isomorphic-starterkit#79]
Firstly, amazing project.
Hitting an issue on IE.
A clean install of the app throws a "Missing ES6 implementation error" for all browsers not natively supporting Promises.

**Comment by RickWong** [comment]
Hi, if browser support for ES6 / ES2015 is an issue then please follow the Babel polyfill guide: https://babeljs.io/docs/usage/polyfill/

**Comment by Jimtattersall** [comment]
Thanks Rick, I tried this but it's still throwing the error.
