### ISSUE TITLE
Fragments dont work

### ISSUE THREAD

**Issue by BespalovAV** [RickWong/react-isomorphic-starterkit#87]
Hi! I've very interesting situation:
https://gist.github.com/BespalovAV/d9c44a82924ba9c32ca8 - no errors, no warnings, just white screen.
If remove fragments from `Transmit.createContainer()`, render is working. What could be the problem?

**Comment by RickWong** [comment]
Add `initialVariables` to the Transmit config. That will mark this Transmit container as **root container**. Only root container queries are fetched automatically. Non-root containers are for composition.

**Comment by RickWong** [comment]
Also, you may want to try [fetch-rest](https://github.com/RickWong/fetch-rest) instead of the standard Fetch API. It supports middleware like transforming `response => response.json()` for every request automatically.

**Comment by tylermadison** [comment]
:+1:

**Comment by BespalovAV** [comment]
It's work! But when I call `Main.getFragment("localContent")` in other component, it is component not render. Gist: https://gist.github.com/BespalovAV/d9c44a82924ba9c32ca8

**Comment by RickWong** [comment]
You've got a circular dependency there. You need to decide whether the Main component imports the Header component, or the other way around.

Having done that, the imported component then does not need `initialVariables` anymore, only the parent.
