### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Download** [RickWong/react-isomorphic-starterkit#88]
So I tried this very promising looking Starter Kit, but unfortunately it does not start on WIndows.

``` sh
> react-isomorphic-starterkit@4.3.0 start C:\ws\react-isomorphic-starterkit
> NODE_PATH="./src" node --harmony ./babel.server

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
...
```

It seems it was actually the very [first issue](https://github.com/RickWong/react-isomorphic-starterkit/issues/1) ever logged for this project and a lot of work has been done to fix it, but somehow it was never completed...

@Semigradsky hit the nail on the head with his last comment:

> It remains to solve the NODE_PATH issue.

So I tried some things... First, just change the `NODE_PATH=...` statement to read `set NODE_PATH=...`:

At first it seems ok, but then it just returns to the command prompt without actually doing anything:

``` sh
C:\ws\react-isomorphic-starterkit>npm run watch

> react-isomorphic-starterkit@4.3.0 watch C:\ws\react-isomorphic-starterkit
> npm run start


> react-isomorphic-starterkit@4.3.0 start C:\ws\react-isomorphic-starterkit
> set NODE_PATH="./src" node --harmony ./babel.server


C:\ws\react-isomorphic-starterkit>
```

Mmmm...  It seems that Windows never executes the second command. Fortunately, we have the `&&` operator which (apparently, I'm not into bash scripting so don't know for sure) is supported both on Windows and *nix... Let's try again with the command changed to `set NODE_PATH=\"./src\"&& node --harmony ./babel.server`:

``` sh
C:\ws\react-isomorphic-starterkit>npm run watch

> react-isomorphic-starterkit@4.3.0 watch C:\ws\react-isomorphic-starterkit
> npm run start


> react-isomorphic-starterkit@4.3.0 start C:\ws\react-isomorphic-starterkit
> set NODE_PATH="./src"&& node --harmony ./babel.server

Error: Cannot find module 'apis/github'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.module._load (C:\ws\react-isomorphic-starterkit\node_modules\piping\lib\launcher.js:24:23)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\ws\react-isomorphic-starterkit\src\server.js:31:15)
```

Mmmm. Now the second command is executed ok, but Node still is not able to resolve the module correctly.

Then I remembered from days long gone of messing around with .bat files, that Windows' `set` command has a very wacky syntax when it comes to quote marks... The opening quote goes _before_ the `set` keyword instead of after the equals sign where you would expect it...
Let's try with this: `set \"NODE_PATH=./src\"&& node --harmony ./babel.server`:

``` sh
C:\ws\react-isomorphic-starterkit>npm run watch

> react-isomorphic-starterkit@4.3.0 watch C:\ws\react-isomorphic-starterkit
> npm run start


> react-isomorphic-starterkit@4.3.0 start C:\ws\react-isomorphic-starterkit
> set "NODE_PATH=./src"&& node --harmony ./babel.server

==> ✅  Server is listening
==> �  Go to http://localhost:8000
webpack built 050d656ffe1454016e7d in 2254ms
```

Presto! 

But of course this code won't run on *nix.... I think  :)

Seems we:
1. Should just use current-script-relative imports i.s.o. project-root-relative ones
2. Should find a util that handles setting env vars in a platform-independent manner

I tried `1.` and it allows us to get rid of the `NODE_PATH` environment variable altogether, at the cost of arguably less attractive import paths... Then again I looked through loads and loads of projects in the last months and using paths the way it is done in this project is very rare. The vast majority of the developers are using current-script-relative paths anyway... 

So e.g. for the import of `apis/github` in `server.js`

``` js
import githubApi from "apis/github";
```

..we could write this instead:

``` js
import githubApi from "./apis/github";
```

This approach would require about 4 or 5 import statements to be changed. Then, we can just drop the `NODE_PATH=...` statement and the start command becomes:

``` sh
node --harmony ./babel.server
```

Arguably, for the purposes of this project, it is much better to have ugly (but standard) import paths and have it work everywhere than have beautiful import paths but not work on Windows... But I leave that up to you to decide.

Good luck and thanks for publishing this project!

**Comment by RickWong** [comment]
I don't mind reversing the "beautiful" import statements for a greater good. If you would make a PR, I'd merge it immediately. 

I'm also (still) working on serverside webpack. That would also solve this issue, and several other webpack-loader related issues.

**Comment by Download** [comment]
Wow fast response! I will create a PR in the coming hour.

**Comment by RickWong** [comment]
Again, thanks!

**Comment by Download** [comment]
@RickWong Can you re-open this? Because your awesome changes to make HMR work (thanks again!) unfortunately have had the side-effect of breaking Windows support again. This due to the use of `rm -rf` in the `scripts` section of `package.json`.

Would you be against the use of Gulp? I feel like converting this project to Gulp to simplify the `scripts` section and do the more complex things in the gulpfile instead.

**Comment by RickWong** [comment]
I've removed the `rm`'s. I don't want to include `gulp`; I use it in other projects but its added value vs. complexity is off IMHO.

**Comment by Download** [comment]
Yeah I too am doubting gulp. But then if I look at the trouble to be cross-platform in the `scripts` section, Gulp does have it's benefits.

If you did the same thing as I did (just remove the `rm -rf ... &&` sections from the `package.json`) then it should work as a charm afterwards. I just tested it and it seems to work great!

One question though? Is it correct I should run `npm run watch` in one cmd window and then `npm start` in a second one? At least that is how I did it and that works. But I wonder if you do it the same way?

**Comment by Download** [comment]
BTW, I think you can achieve cross-platform `rm -rf` using [rimraf](https://www.npmjs.com/package/rimraf). Because probably cleaning up before watching is a good idea.

**Comment by RickWong** [comment]
npm run watch should be enough, isnt it for you?

**Comment by Download** [comment]
I don't think it was. The server did not start I think.

**Comment by RickWong** [comment]
@Download  It works fine for me, freshly but also repeatedly. Can you paste the console output here?

**Comment by RickWong** [comment]
I see, you should probably increase the --delay option in the "watch-server" command.

**Comment by Download** [comment]
@RickWong Yes! Actually, better would probably be to watch the dev-server and only start the server once the dev-server is up. I have experimented a bit and if I poll an HTTP request to the dev server address and continue only once it's up (or 30s timeout expired) then it never seems to fail.

I wrote some code for it myself now, but later (of course afterwards doh!) I found a library that seems to do exactly that [wait-up](https://www.npmjs.com/package/wait-up).

My code is working fine now, but if you want to make it more robust than using a delay, wait-up seems a simple option. Technically you would also have to wait for the server JS file to be generated after it was deleted (using a watch?), but for me it's working without that extra check, probably because I'm starting the webpack process for the server-side first so it gets a small head-start on the webpack process for the client-side. Could just be luck of course :)

**Comment by RickWong** [comment]
Seriously, that's clever! Please make a pull request to add wait-up. I'll merge it asap.

**Comment by RickWong** [comment]
I have some time left, I'll give it a go.

**Comment by RickWong** [comment]
It's done. :)

**Comment by Download** [comment]
Thanks! You almost got it right.

It seems that Windows trips over the use of single quotes. I had to replace `'dist/*.js'` with `\"dist/*.js\"` in script `watch-server-start` in `package.json`.

See my pull request which fixes this.
