### ISSUE TITLE
(piping) Koa + webpack-hot-middleware loses WebSocket connection when server restarts

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-isomorphic-starterkit#90]
Started using webpack-hot-middleware since a recent version, but just noticed that when piping restarts the Koa server, it also disconnects the webpack HMR client's WebSocket connection. This breaks client updates.

The only way to solve this currently is to **disable piping** for now if you want client updates. Sorry for this inconvenience.

**Comment by RickWong** [comment]
Fixed by reverting to webpack-dev-server. (And also because we now use Webpack for the serverside, it's impossible to use webpack-dev-middleware and webpack-hot-middleware anymore.)

**Comment by amcsi** [comment]
But then syntax-errors cannot be react-redboxed if you don't use webpack-dev-middleware and webpack-hot-middleware I believe; you're removing an important dev tool.

**Comment by RickWong** [comment]
It's impossible to combine serverside webpack with webpack-dev-middleware because the latter cannot be bundled. 

Why wouldn't react-redboxed work with webpack-dev-server?

**Comment by amcsi** [comment]
The server-side doesn't need to be, it can stay as it is.

When I was trying to set react-redbox up with webpack-dev-server, I couldn't get it working. I had to use webpack-dev-middleware.

gaearon (Dan Abramov) is also using webpack-dev-middleware here: https://github.com/gaearon/react-transform-boilerplate

> Syntax errors are displayed in an overlay using @glenjamin’s webpack-hot-middleware, which replaces Webpack Dev Server. This project does not use React Hot Loader.

**Comment by RickWong** [comment]
All that you've mentioned, I already know. 

Again, the server-side uses Webpack for server-side HMR and webpack loaders. webpack-dev-middleware can not be bundled by Webpack because of technicalities. That's why I had to revert that change.

If you've got an issue setting up React redbox please make a separate issue about it.

**Comment by amcsi** [comment]
So wait, you already support syntax-error catching with react-redbox too? In that case I'll try actually running this project. I actually have my own project not based on this one, but I'm taking a lot of ideas from here :P

**Comment by amcsi** [comment]
Okay I tried your project by cloning master, npm installing, then doing npm run watch, and no, there is no react-redbox if I write a blatant syntax error in Main.js

It just refreshes the page

Which points to that webpack-dev-middleware is needed if you want hmr with react-redbox with syntax errors

**Comment by RickWong** [comment]
Apparently https://github.com/gaearon/react-transform-catch-errors is needed to catch errors. I will try to add it.

**Comment by RickWong** [comment]
@amcsi Did you use the development build with `npm run watch`? It works for me. I get a nice red screen with the error.

If you use the production command `npm run start` then `babel-preset-react-hmre` is not configured and therefore `redbox-react` will not work.

**Comment by amcsi** [comment]
Argh this is confusing
Okay so first I want to put it out there that gaearon himself said that for react-redbox to work with not just errors happening in render() methods (like it can inherently with react-transform-catch-errors), but also with syntax errors or any other error happening outside of render() methods, webpack-dev-server is not good enough:
https://github.com/KeywordBrain/redbox-react/issues/36#issuecomment-167248365

Secondly, I wanted to test again with your project so I could confirm that react-redbox does work, just not with syntax errors. However, I actually didn't get a redbox, but just a page refresh even with a throw within a render() method.

I might be doing something wrong though; what I did was:
1. npm run watch
2. go to http://localhost:8000/
3. write a syntax error outside the Main.js component definition (as expected, resulted in page refresh)
4. attempted to write a throw 'lol' in the render() method (unexpectedly the page refreshed when I was actually expecting this to work even with webpack-dev-server)

Could you try one thing for me? Please try to type this before `class Main extends React.Component {`:

asdfasdf dsafadsf

^ a blatant syntax error like that outside of the React component definition. Are you still getting the react-redbox like it would be cool to?

**Comment by RickWong** [comment]
Previously I tried just regular errors, not syntax errors. Now I can confirm that syntax errors do not show in `redbox-react`.

Dan Abramov is right. And there seems no way to prevent the Webpack page reload. I'll look into this when I have time. Perhaps there is some undocumented setting.

**Comment by RickWong** [comment]
@amcsi  You can set `config.devServer.inline` to `false` in webpack.client-watch.js to prevent the page reload! Webpack will update the page again after you fix the syntax error. 

Is that good enough?

**Comment by amcsi** [comment]
@RickWong I tried and yes it seems to not do the refresh, which is good in the sense that I get to keep my state, although it does have a slight flaw that now there's no visual clue on the page that some sort of error happened. By the way I'm still not able to reproduce a redbox at all, even when I throw an exception within render()

It's still not as good as displaying syntax errors in a big red box.

I recommend you to see Dan Abramov's video about Hot Reloading with Time Travel to see visually how useful it is that you get a red box when any kind of error happens while developing: https://www.youtube.com/watch?v=xsSnOQynTHs

I think this feature would be really important

**Comment by RickWong** [comment]
@amcsi Try this in the `render()` function of Main.js:  `throw Error("Hello world");` It works for me.

**Comment by amcsi** [comment]
With that the redbox does appear. I know it was complaining before in the console when I did `throw "lol"` in the render() method that the thrown value was expected to be an instance of Error when it was actually a string.

**Comment by RickWong** [comment]
I'll leave the issue where it's at right now. Not fully reloading the page makes it possible to keep state. That's good enough at the moment. Thanks for debugging it with me!

**Comment by amcsi** [comment]
No problem, good luck with your project which seems really promising!
