### ISSUE TITLE
Suggestion: Remove Transmit?

### ISSUE THREAD

**Issue by richardanaya** [RickWong/react-isomorphic-starterkit#92]
I know there is a lot that could be added to this starterkit.  But I found this a distraction when I was getting setup with this starter kit.  I think its a cool project. But when I came to this starterkit, I didn't really want to have to look through a new databinding tech.

**Comment by RickWong** [comment]
It's part of the isomorphic example app. If you inspect the HTML output of the first request then you'll see part of the data is served with it. So I believe a library like Transmit is crucial to making an app isomorphic (rendering correctly without client-side JS). To remove it would mean to having to replace it with something similar.

**Comment by richardanaya** [comment]
Is there a simpler way to provide data to the first request?

**Comment by RickWong** [comment]
Depends on what you mean by "simple". If by simple you mean without a library like Transmit, then you'll end up with more duplicate code you write yourself to fetch data on the server and refetch everything on the client. Additionally you'll have to make sure that the data is exactly the same, so React can pick up from the first HTML output and continue. (Otherwise React will drop the first HTML output and start from scratch on the client.) Then you'd waste bandwidth on fetching and CPU cycles on rendering.

**Comment by richardanaya** [comment]
By simpler I mean, with the fewest technologies possible. Transit's purpose seems to be data fetching from what I understand.  I'm just beginning isomorphic react, but I'm not sure why the data you handed off to the front end would be different than the data you rendered with on the backend.

**Comment by richardanaya** [comment]
A part of me is just wondering if it is overkill, I guess I have similar feeling to react-inline-css. Peoples use all sorts of different ways to do styles ( style sheets, inline, or relying on a ui framework). I feel like you're recommending people do certain things, perhaps i've not seen yet why you suggest them, but for a developer I feel like I already have other technology choices than yours I want to use and i'm really just interested in the most simplest react isomorphic setup to begin from.

**Comment by RickWong** [comment]
>  I'm not sure why the data you handed off to the front end would be different than the data you rendered with on the backend.

Like I said, you end up with more code you have to write, and you'd be wasting server AND client time. Your users would be waiting for the server fetching+rendering and then again for the client fetching+rendering. Simpler? Perhaps, I don't know. Isomorphic? Nope.

> similar feeling to react-inline-css

You should just use whatever you feel comfortable with. React InlineCss is small and uncoupled enough to delete in a matter of seconds. You could replace it with Radium or any other style library.

> recommending people do certain things

I understand that it can be overwhelming. For this reason I decided not to include any Flux/Redux library. But to illustrate the "isomorphic" point, some decisions had to be made. Like Koa for the web server, some people actually prefer Hapi or Express. Like React Router, some people might prefer a Redux-based router. By all means, take from this starterkit the lessons and example code, and create your own home-grown starterkit. I'm not forcing anyone to use it as-is. I mean, it's a starterkit, not a framework.

**Comment by richardanaya** [comment]
Sure, just giving feedback, I appreciate the starterkit anyways, it's the best one i've found around this configuration.

**Comment by RickWong** [comment]
Thanks! And thank you for posting this question and reminding me of this: Sometimes it's healthy to go over past decisions and see again if there's a need for change!
