### ISSUE TITLE
[question] Clarification to the existance of webpack.server.js

### ISSUE THREAD

**Issue by ghost** [RickWong/react-isomorphic-starterkit#97]
Can you provide a bit of context around why the webpack.server.js is needed?

**Comment by RickWong** [comment]
1) Webpack Hot Module Reloading (webpack.server-watch.js) and 2) requiring ES2015/ES7 and non-JS files with Webpack-loaders (Babel and CSS etc).

**Comment by ghost** [comment]
So these are both for development workflow and wouldn't be used in production, correct?

**Comment by RickWong** [comment]
No, Webpack HMR in point 1 is development only. 

Bundling and transforming via Webpack-loaders in point 2 also happens for the production build. Node doesn't understand `require("...css")` for example, so building the production build is a must.

**Comment by ghost** [comment]
Ah, that makes more sense. Thanks for the answers. Much appreciated.
