### ISSUE TITLE
Clarification on Transmit

### ISSUE THREAD

**Issue by thehashrocket** [RickWong/react-isomorphic-starterkit#99]
I'm hoping to understand the purpose of Transmit in the app. I'm still learning React and there's many ways of doing things it seems. Here's my question:

Without this code:

```
/**
 * Use Transmit to query and return GitHub stargazers as a Promise.
 */
export default Transmit.createContainer(Main, {

});
```

Then the container doesn't return anything.

Compare that to this style:

```
export default class Home extends Component {
  render() {
    const styles = require('./Home.scss');
    // require the logo image both from client and server
    const logoImage = require('./logo.png');
    return (
      <div className={styles.home}>
        <p>Some stuff in here, yo.</p>
      </div>
    );
  }
}
```

Why the difference?

Also, I'm wondering if I can include components and stores? Is this a Flux pattern or something different?

**Comment by RickWong** [comment]
The first question: the starterkit uses `Transmit.render()` and `Transmit.renderToString()` so it expects the component to be a valid Transmit component. Do you get an error message in the console?

The second question: Transmit does not attempt to solve any `require()` problems. It solves the problem that if your components are dynamically composed according to some data, the server and client will render the same thing.  For example: let's say you retrieve 10 "posts" from your database and render them on the server. How do you get those 10 "posts" to the client-side so those React can render those on the client-side? Transmit helps you bring that kind of dynamic data from server to client.

**Comment by thehashrocket** [comment]
So, I have been able to work something out this way:

Here's my base file, like a Template if you will:

```
import React from "react";
import InlineCss from "react-inline-css";
import Transmit from "react-transmit";
import { Test } from "components";

class App extends React.Component {
    /**
     * Runs on server and client.
     */
    render () {

        return (
            <InlineCss stylesheet={`
                & .card {
                    cursor: pointer;
                    margin: 15px;
                    padding: 15px;
                    text-align: center;
                    height: 200px;
                }
                & img {
                    width: 130px;
                    height: 130px;
                }
                & p {
                    margin: 10px;
                }
                `}>
                <div>
                    <h1>
                        REGULAR PAGE
                    </h1>
                    <Test/>
                    <p>This format will work too, it appears.</p>

                    {this.props.children}

                </div>
            </InlineCss>

        );
    }
}
export default App;
```

That works with no problems.

`{this.props.children}` receives the component from `IndexRoute` and `Classrooms` subcomponent is popped in it's place.

Since my routes look like this:

```
    <Router history={browserHistory}>
        <Route path="/" component={App}>
            <IndexRoute component={Classrooms}/>
        </Route>
        <Route path="/about" component={Home}/>
        <Route name="RegularPage" path="/RegularPage" component={RegularPage} />
    </Router>
```

`/about` pulls up the example homepage which comes in the starter kit. So Transmit still works.

One question I have, and I'm hoping you can clarify, is that I'm using InlineCSS in the App class (as you can see above) and i'm seeing an error in the console log:

![Console log errors](http://i.imgur.com/xeosB2n.png)

Any idea how I could work around this?

**Comment by RickWong** [comment]
> Any idea how I could work around this?

The easiest way is to set the `namespace` prop manually to something unique. Then InlineCss will use that instead of the (badly) random-generated id.
